### ISSUE TITLE
页面横向滑动时，下划线过渡有点卡顿。

### ISSUE THREAD

**Issue by aijason** [itenl/react-native-scrollable-tabview#20]
页面横向滑动时，下划线过渡有点卡顿。

**Comment by itenl** [comment]
请问是 Dev 还是 Release 环境?

**Comment by aijason** [comment]
dev 打出来android release也还有这个问题，就是在过渡到下一个Tab时下划线和字体的颜色切换会顿一下。

**Comment by itenl** [comment]
这是源码上的实现 `useNativeDriver: !tabsEnableAnimatedUnderlineWidth && !__DEV__`
在开发调试模式下是不会启用 `useNativeDriver` , 而 Release 后在不丢帧的情况下流畅程度将会大有改善，跳跃Tabs是使用 `translateX` && `scaleX` 组合实现可能存在不同设备兼容问题，条件允许可以提供代码块与视频或GIF检查具体情况。
