### ISSUE TITLE
请问该组件是否已用于生产环境？

### ISSUE THREAD

**Issue by ZhaoTim** [itenl/react-native-scrollable-tabview#22]
HI：
偶然发现这个神奇的组件，看上去会火。
所以好奇，该组件是否已经用于生产环境呢？
以及，有对应的群组吗，类似于微信群吗！想加群一起探讨哈。

**Comment by itenl** [comment]
谢谢，目前该项目已投入到生产环境使用，后续有一定需求时可以组建Discord探讨交流，以及该项目API较多后续计划升级TS版本，可持续关注。

**Comment by ZhaoTim** [comment]
> 谢谢，目前该项目已投入到生产环境使用，后续有一定需求时可以组建Discord探讨交流，以及该项目API较多后续计划升级TS版本，可持续关注。

似乎没有大佬的邮箱，可否留一下呢？

**Comment by itenl** [comment]
Email `nesa.wong@gmail.com`
Discord `k.louis#4049`
