### ISSUE TITLE
嵌套Flatlist会有手势冲突的问题

### ISSUE THREAD

**Issue by BcueB1U3** [itenl/react-native-scrollable-tabview#24]
Hi~
找了一圈类似的组件还是认为大佬你这个组件的功能更全~
有个小问题就是嵌套Flatlist的话会有手势冲突的问题，是否有方法能够修复这个问题呢。
如果像demo里面用多个View组成列表，数据量大的话对性能不太友好

**Comment by itenl** [comment]
谢谢支持，其中针对数据体量大的需要作额外优化，不作瀑布流式布局，及动态计算高度不会有太大问题。
垂直嵌套滚动 FlatList 请查看 [Demo](https://github.com/itenl/react-native-scrollable-tabview-example-tiktok/blob/main/App.js#L82)

横向嵌套滚动请使用 
``` javascript
import { ScrollView, FlatList } from 'react-native-gesture-handler';
<ScrollView horizontal={true} showsHorizontalScrollIndicator={false} showsVerticalScrollIndicator={false}>
  {[1, 2, 3, 4, 5].map((item, index) => {
    return (
      <View style={{ width: 120, height: 30, borderWidth: 1, borderColor: 'pink' }}>
        <Text>{JSON.stringify(item)}</Text>
      </View>
    );
  })}
</ScrollView>
<FlatList
  data={[1, 2, 3, 4, 5]}
  showsHorizontalScrollIndicator={false}
  showsVerticalScrollIndicator={false}
  horizontal
  renderItem={() => {
    return (
      <View style={{ width: 120, height: 30, borderWidth: 1, borderColor: 'pink' }}>
        <Text>{JSON.stringify(item)}</Text>
      </View>
    );
  }}
/>
```

**Comment by BcueB1U3** [comment]
> 谢谢支持，其中针对数据体量大的需要作额外优化，不作瀑布流式布局，及动态计算高度不会有太大问题。 垂直嵌套滚动 FlatList 请查看 [Demo](https://github.com/itenl/react-native-scrollable-tabview-example-tiktok/blob/main/App.js#L82)
> 
> 横向嵌套滚动请使用
> 
> ```js
> import { ScrollView, FlatList } from 'react-native-gesture-handler';
> <ScrollView horizontal={true} showsHorizontalScrollIndicator={false} showsVerticalScrollIndicator={false}>
>   {[1, 2, 3, 4, 5].map((item, index) => {
>     return (
>       <View style={{ width: 120, height: 30, borderWidth: 1, borderColor: 'pink' }}>
>         <Text>{JSON.stringify(item)}</Text>
>       </View>
>     );
>   })}
> </ScrollView>
> <FlatList
>   data={[1, 2, 3, 4, 5]}
>   showsHorizontalScrollIndicator={false}
>   showsVerticalScrollIndicator={false}
>   horizontal
>   renderItem={({ item }) => {
>     return (
>       <View style={{ width: 120, height: 30, borderWidth: 1, borderColor: 'pink' }}>
>         <Text>{JSON.stringify(item)}</Text>
>       </View>
>     );
>   }}
> />
> ```

好的谢谢~

**Comment by BcueB1U3** [comment]
> 谢谢支持，其中针对数据体量大的需要作额外优化，不作瀑布流式布局，及动态计算高度不会有太大问题。 垂直嵌套滚动 FlatList 请查看 [Demo](https://github.com/itenl/react-native-scrollable-tabview-example-tiktok/blob/main/App.js#L82)
> 
> 横向嵌套滚动请使用
> 
> ```js
> import { ScrollView, FlatList } from 'react-native-gesture-handler';
> <ScrollView horizontal={true} showsHorizontalScrollIndicator={false} showsVerticalScrollIndicator={false}>
>   {[1, 2, 3, 4, 5].map((item, index) => {
>     return (
>       <View style={{ width: 120, height: 30, borderWidth: 1, borderColor: 'pink' }}>
>         <Text>{JSON.stringify(item)}</Text>
>       </View>
>     );
>   })}
> </ScrollView>
> <FlatList
>   data={[1, 2, 3, 4, 5]}
>   showsHorizontalScrollIndicator={false}
>   showsVerticalScrollIndicator={false}
>   horizontal
>   renderItem={({ item }) => {
>     return (
>       <View style={{ width: 120, height: 30, borderWidth: 1, borderColor: 'pink' }}>
>         <Text>{JSON.stringify(item)}</Text>
>       </View>
>     );
>   }}
> />
> ```

现在有一个新问题就是切换tab的时候，里面的Screen会出现遮罩效果，有点像设置了opacity

**Comment by BcueB1U3** [comment]
> 好的谢谢~
> 
> 现在有一个新问题就是切换tab的时候，里面的Screen会出现遮罩效果，有点像设置了opacity，切换的第3次tab就会出现这种情况。
> 
> react-native：0.63.4 ios：14.5
> 
> <img alt="1" width="372" src="https://user-images.githubusercontent.com/39724843/143184495-689205f5-9fd5-4b27-b56d-3abbbe443c86.png">
> 
> <img alt="2" width="366" src="https://user-images.githubusercontent.com/39724843/143184503-5fa39339-8f86-4e6d-9c34-4643d122d528.png">
> 
> ```
> initStacks = () => {
>     return [
> 	  {
> 		  screen: TestPage2,
> 		  tabLabel: "1",
> 	  },
> 	  {
> 		  screen: TestPage2,
> 		  tabLabel: "2",
> 	  },
> 	  {
> 		  screen: TestPage2,
> 		  tabLabel: "3",
> 	  },
>     ]
> }
> 
> <SafeAreaView style={styles.container}>
>   <ScrollableTabView
>     ref={this.scrollableTabView}
>     stacks={this.initStacks()}
>     firstIndex={0}
>     syncToSticky={true}
>     onEndReachedThreshold={0.1}
>     header={() => {
>     return <View style={{ backgroundColor: 'green', height: 120 }}></View>;
>     }}
>   ></ScrollableTabView>
> </SafeAreaView>
> 
> 
> 
> // TestPage2：
> render() {
>   return (
>     <View style={
>         {
> 	    flex: 1,
> 	    backgroundColor: "red",
> 	    justifyContent: "center",
> 	    alignContent: "center",
> 	    alignItems: "center"
>         }} >
>     </View>
>   )
> }
> ```



我设置了一下<AnimatedCarousel  ...  inactiveSlideOpacity={1} /> 就没有这个问题了，有可能是这个的原因😄

**Comment by itenl** [comment]
是的，如你所述需要添加该项属性，其中这些参数是三方组件属性，非核心属性从上几个版本已剔除，可以交由 `carouselProps` 传递覆盖。
```javascript
<ScrollableTabView
  ref={it => (this.scrollableTabView = it)}
  carouselProps={{
    inactiveSlideOpacity: 1,
  }}
/>
```

**Comment by BcueB1U3** [comment]
如果嵌套Flatlist的话，每个tab的Screen的上下滑动距离都是共享的，比如1个tab向下滑动了200，切换到第3个tab滑动到顶部，这样切回到第1个tab的话也会跟着回到顶部。是否有方法可以处理这种问题呢？

**Comment by itenl** [comment]
该项功能还未列入开发计划，可用临时解决方案代替，于缓存位置后在切换视图时使用 `_scrollTo ` 进行指定 `viewOffset `

**Comment by BcueB1U3** [comment]
> 该项功能还未列入开发计划，可用临时解决方案代替，于缓存位置后在切换视图时使用 `_scrollTo ` 进行指定 `viewOffset`

好的谢谢
