### ISSUE TITLE
即将删除生命周期警告修复

### ISSUE THREAD

**Issue by shier-c** [itenl/react-native-scrollable-tabview#25]
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.
![image](https://user-images.githubusercontent.com/48742768/143733957-9337318d-de44-4127-8a96-158e90152e89.png)

**Comment by itenl** [comment]
是的，已知问题，将在后续版本进行更新

**Comment by shier-c** [comment]
> 

还有个问题如果想刷新整个页面有没有钩子
