### ISSUE TITLE
Question stacks

### ISSUE THREAD

**Issue by AlexCernik** [itenl/react-native-scrollable-tabview#28]
hi, is possible create stacks statics? without reload or onEndReached?

Is possible disable this option?

my stack
```javascript
const first = () => {
  return (
    <View style={{flex:1}}>
      <Text>Hola</Text>
      ...
    </View>
  );
}
```

**Comment by itenl** [comment]
> hi, is possible create stacks statics? without reload or onEndReached?
> 
> Is possible disable this option?
> 
> my stack
> 
> ```js
> const first = () => {
>   return (
>     <View style={{flex:1}}>
>       <Text>Hola</Text>
>       ...
>     </View>
>   );
> }
> ```

It is not currently supported, but this suggestion is good idea, the functional component will be more flexible, and will be supported in the future, `onRefresh` / `onEndReached` will be converted to `useRefresh` / `useEndReached`.

**Comment by AlexCernik** [comment]
> 

and i too are received warning:
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.  in ScrollableTabView

**Comment by itenl** [comment]
> and i too are received warning: Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method. in ScrollableTabView

i trying to find the wrong location, and u can try to use `patch-package` to make temporary corrections.

```javascript
 componentWillUnmount() {
    this.setState = (state, callback) => {
      return;
    };
  }
```

**Comment by itenl** [comment]
Hey @AlexCernik regarding the use of `onRefresh` / `onEndReached` in the function component, `v1.1.7` already supported. 
[refer to](https://github.com/itenl/react-native-scrollable-tabview-example-tiktok/blob/24adec66bde6b6bedddfebd01445ec71cab96706/App.js#L645)  
And in the function component, must call `initScreen`.
