### ISSUE TITLE
scrollableTabV.scrollTo is not function

### ISSUE THREAD

**Issue by daizhenhong** [itenl/react-native-scrollable-tabview#29]
I use scrollTo for change tab, but error as the message 'TypeError._this3$scrollableTabV.scrollTo is not function.(In "_this3$scrollableTabV.scrollTo(_this3.state.firstIndex)"

it the package.json for scrollable info:
```
"react": "16.11.0",
"react-native": "^0.62.2",
"react-native-scrollable-tab-view": "^0.8.0",
```

![image](https://user-images.githubusercontent.com/13689340/147468302-9e1eae28-3a41-43ef-a94d-8edce6373355.png)

**Comment by AlexCernik** [comment]
Hola, el paquete es `@itenl/react-native-scrollable-tabview`
 y no `react-native-scrollable-tab-view`.

**Comment by itenl** [comment]
> I use scrollTo for change tab, but error as the message 'TypeError._this3$scrollableTabV.scrollTo is not function.(In "_this3$scrollableTabV.scrollTo(_this3.state.firstIndex)"
> 
> it the package.json for scrollable info:
> 
> ```
> "react": "16.11.0",
> "react-native": "^0.62.2",
> "react-native-scrollable-tab-view": "^0.8.0",
> ```
> 

Name              | Type     | Description
----------------- | -------- | -----------
**`toTabView(index: number.required / label: string.required)`**            | Function   | Jump to the specified Screen
**`scrollTo(index: number.required)`**            | Function   | Swipe up and down to the specified position (passing in 0 is the default positioning to tabs / passing in a negative number is set to the top)

Maybe u want jump to other stack/screen, try it `toTabView`.

**Comment by daizhenhong** [comment]
> 

It is resolved use toTabView. yes ,I want to jump to other stack/screen
