### ISSUE TITLE
cannot run in web

### ISSUE THREAD

**Issue by edward1986** [itenl/react-native-scrollable-tabview#32]
cannot run in web, /node_modules/@itenl/react-native-scrollable-tabview/src/index.js 27:19
Module parse failed: Unexpected token (27:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. Se

**Comment by itenl** [comment]
[Link](https://github.com/itenl/react-native-scrollable-tabview-example-tiktok/issues/1#issuecomment-1171894356)
